-- ====================================================================
-- SmartCare Time Slots & Consultations Expansion
-- Run this in your Supabase SQL Editor.
-- ====================================================================

-- 1. Modify appointments table
ALTER TABLE public.appointments 
  ADD COLUMN IF NOT EXISTS visit_type TEXT DEFAULT 'new' CHECK (visit_type IN ('new', 'follow_up')),
  ADD COLUMN IF NOT EXISTS follow_up_of BIGINT REFERENCES public.appointments(id),
  ADD COLUMN IF NOT EXISTS slot_start TIME,
  ADD COLUMN IF NOT EXISTS slot_end TIME;

-- 2. Create partial unique index to prevent double-booking 
--    (excludes cancelled appointments)
DROP INDEX IF EXISTS idx_uq_appointments_slot;
CREATE UNIQUE INDEX idx_uq_appointments_slot 
  ON public.appointments (doctor_id, appointment_date, slot_start)
  WHERE status != 'cancelled';

-- 3. Create doctor_schedules table
CREATE TABLE IF NOT EXISTS public.doctor_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
  day_of_week INT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0=Sun, 1=Mon...
  start_time TIME NOT NULL DEFAULT '09:00',
  end_time TIME NOT NULL DEFAULT '17:00',
  slot_duration_minutes INT NOT NULL DEFAULT 15,
  active BOOLEAN NOT NULL DEFAULT true,
  UNIQUE(doctor_id, day_of_week)
);

-- Enable RLS on doctor_schedules
ALTER TABLE public.doctor_schedules ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read schedules (for booking)
DROP POLICY IF EXISTS "Authenticated users can read schedules" ON public.doctor_schedules;
CREATE POLICY "Authenticated users can read schedules" 
  ON public.doctor_schedules FOR SELECT 
  TO authenticated USING (true);

-- Allow admins to manage schedules
DROP POLICY IF EXISTS "Admins can manage schedules" ON public.doctor_schedules;
CREATE POLICY "Admins can manage schedules" 
  ON public.doctor_schedules FOR ALL 
  TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Allow doctors to manage their own schedules
DROP POLICY IF EXISTS "Doctors can manage own schedules" ON public.doctor_schedules;
CREATE POLICY "Doctors can manage own schedules" 
  ON public.doctor_schedules FOR ALL 
  TO authenticated USING (doctor_id = public.get_doctor_id()) WITH CHECK (doctor_id = public.get_doctor_id());

-- 4. Seed default schedules for all existing doctors (Mon-Fri)
DO $$
DECLARE
  doc RECORD;
  day INT;
BEGIN
  FOR doc IN SELECT id FROM public.doctors LOOP
    FOR day IN 1..5 LOOP
      INSERT INTO public.doctor_schedules (doctor_id, day_of_week, start_time, end_time, slot_duration_minutes)
      VALUES (doc.id, day, '09:00', '17:00', 15)
      ON CONFLICT (doctor_id, day_of_week) DO NOTHING;
    END LOOP;
  END LOOP;
END $$;
